### ISSUE TITLE
biojs 2 meta bug

### ISSUE THREAD

**Issue by wilzbach** [biojs/biojs#99]
(meta bug to track all open issues for the next big release: biojs 2.0)
- [x] [Events.json](https://github.com/biojs/biojs/issues/96)
- [ ] review tutorial
- [x] more migrated components
- [ ] visualization guides? (e.g. [edu](http://edu.biojs.net/series/101/40_visualization_basic.html))
- [ ] [getting started for lazy dev](https://github.com/biojs/registry-ui/issues/13)
- [ ] [Event system?](https://github.com/biojs/biojs/issues/95)
- [ ] [Gold standard](https://github.com/biojs/edu/issues/3)
- [ ] [Example projects](https://github.com/biojs/edu/issues/4)
- [ ] [integration guides](https://github.com/biojs/biojs/issues/86)
